### PR TITLE
Support Ecto 2.2.0

### PR DESCRIPTION
**Pull request by erikreedstrom**
These changes allow for the the library to work with changes presented in the current state of Ecto 2.2.0-rc.0.

Adds additional match for `{name, source, type}` supporting the new `source` option on field.

Updates test for persisting non-schema attributes as new warning is emitted when passing a different schema type to relation.

### CODE REVIEW

**Comment by yordis** [comment]
@schrockwell hey man, is there any possibility that we can get this into master and release before the end of the week?

**Comment by paulcsmith** [comment]
Thanks so much @erikreedstrom. Going to merge this in and try to get it out by end of week after some testing!

**Comment by schrockwell** [comment]
@yordis Sorry, maybe I'm missing something, but not sure why I'm needed here?

**Comment by yordis** [comment]
@schrockwell yeah sorry @paulcsmith merged 20 minutes ago 😄

**Comment by KamilLelonek** [comment]
When is it going to be published in the `hex` repository?

**Comment by stefkin** [comment]
It would be great to roll the new version out sooner, ecto 2.2 has crucial bugfixes.

**Pull request merged**
