### PR TITLE
Always compile Ecto

### PR DESCRIPTION
**Pull request by jsteiner**
ExMachina may be used in other environments.

### CODE REVIEW

**Comment by paulcsmith** [comment]
I don't think this is the solution. We shouldn't require Ecto as a dependency, instead I think we want to change all the `%Ecto...{}` structs to `%{__struct__: Ecto...}`

**Comment by jsteiner** [comment]
Ah, yeah, that makes more sense. I see that now in the other PR. Doing a not so great job at multitasking...

**Comment by paulcsmith** [comment]
Haha it's all good. Multitasking is hard :)

**Comment by jsteiner** [comment]
Merged.

**Pull request closed without merging**
